apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
        gcp-auth-skip-secret: "true"
    spec:
      containers:
        - name: service1
          image: europe-west1-docker.pkg.dev/kamaalio/kubernetes-learnings/service1:v1
          imagePullPolicy: Always
