apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: europe-west1-docker.pkg.dev/kamaalio/kubernetes-learnings/service1:v1
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service1-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
