set export

PORT := "8000"

CONTAINER_NAME := "service1"

default:
    just --list

build:
    docker build -t $CONTAINER_NAME .

run: stop-and-remove-container
    docker run -dp $PORT:$PORT --name $CONTAINER_NAME -e PORT=$PORT $CONTAINER_NAME

build-run: build run

run-dev:
    bun dev

[private]
stop-and-remove-container:
    docker stop $CONTAINER_NAME || true
    docker rm $CONTAINER_NAME || true
